spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homeWork33
    driver-class-name: org.h2.Driver
    username: ${userName}
    password: ${password}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: INFO
    org.springframework.web: INFO
